services:
  app:
    profiles: ["local"]
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local
    networks:
      - default
    depends_on:
      - db

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge